### ISSUE TITLE
Curling vs Stretching

### ISSUE THREAD

**Issue by onnonym** [dariogoetz/noted-layout#6]
Hi, this less of an issue and more of a question. Curling your finger is easier than stretching it. This is even included in your layout optimizer. However, 'a' ends up in the top row, while 'ä' goes to the lower row, despite both being actuated by the index finger. If I try switching them (and u/ü) in the optimizer, I end up with a much worse score. Is there an easy explanation for this?

**Comment by dariogoetz** [comment]
I'm not sure if the explanation is easy, but I'll try.

The "curling" vs. "stretching" difference is taken into account in the `finger repeats` metric. So it only applies to bigrams of symbols that are hit with the same finger in the layout, e.g., `ea` or `rl`. When I switch `a` and `ä` in the optimizer, the finger repeats metric actually decreases (as you expected with the penalty for "stretching" being higher than the one for "curling").

However, some of the other metrics now deteriorate for various reasons. For instance, the `key cost` metric gets a higher value because the `a` is much more frequent and now in a slightly worse position (cost 14 vs cost 12 in the default config for a row-staggered keyboard due to the right-shift of the lower row). Also the `movement pattern` metric measuring "uncomfortable" movements that are not finger repeats gets slightly worse (though I don't know which exact bigrams or movements are the ones responsible in this case - one would need to have a look at more than the worst three bigrams to see the difference).

All in all, this leads to a worse total score even if the "curling" vs. "stretching" effect is actually relieved.
