### ISSUE TITLE
Modifiers broken on Debian Testing

### ISSUE THREAD

**Issue by MaxG87** [dariogoetz/noted-layout#8]
I recently switched from Debian Stable to Debian Testing. I replaced the pre2.39 layout with the more recent one.

I activate the layout using `setxkbmap noted` and thus use the noted file.

Unfortunately, several things are broken now that worked before. I think it all boils down to Mod3 and Mod4 do not work anymore. Therefore, I cannot enter any special characters (I couldn't exit VIM ;-).). Also the arrow keys under the left hand, which I use a lot, do not work anymore.

**Comment by dariogoetz** [comment]
Hi @MaxG87,

I do not use Debian myself, but tried reproducing your issues within a Virtualbox Debian installation. I was not able to reproduce the issue (in GNOME on Xorg).
Note, however, that when using GNOME on wayland, the `setxkbmap noted` command will not work because (to my knowledge) it is an X11 command and wayland handles keyboard layouts differently.
For reproducing the issue, I tried "GNOME classic on Xorg", "GNOME on Xorg", LXDE and Openbox. I do have issues with CAPSLOCK being used as M3 (this might be an issue due to the Virtualbox setup, I don't know), M3 on the right hand as well as both M4 work all right, though.

What WM/DE are you using? Is it running on X11 or on wayland? Does your DE provide extra settings for adjusting keyboard settings (newer GNOMEs have some separate graphical dialog, where e.g. CAPSLOCK behavior can be specified).

**Comment by MaxG87** [comment]
I use KDE on X11 from Debian Testing. Thus it is from the 5.X family.

I tried to reproduce on a different machine with Testing and the modifiers work as expected. I will try on the original computer tomorrow again and report back.

**Comment by MaxG87** [comment]
Now it works on the other machine too. Sorry for the trouble caused.
